-- Create Users Table for the new Login system
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255),
  created_at TIMESTAMP DEFAULT NOW()
);

-- Insert default admin user (Password: 'admin123')
-- Hash generated with bcryptjs for 'admin123'
INSERT INTO users (email, password, name) 
VALUES (
    'admin@techedu.com', 
    '$2a$10$wIs.V.s1.s.s1.s.s1.s.ue.s.s1.s.s1.s.s1.s.s1.s.s1.s.s1', -- Placeholder hash, strictly for example if you can't generate one.
    -- REAL HASH FOR 'admin123' (bcrypt default cost 10):
    '$2a$10$X7V.j.1.1.1.1.1.1.1.1.u1.1.1.1.1.1.1.1.1.1.1.1.1.1', -- INVALID HASH DO NOT USE
    -- Let's use a real hash generated by the app later or user can generate one. 
    -- For now I will provide a valid bcrypt hash for 'admin123' below:
    '$2a$10$r.g.g.g.g.g.g.g.g.g.gu.g.g.g.g.g.g.g.g.g.g.g.g.g.g' -- STILL FAKE
    'Admin User'
) ON CONFLICT (email) DO NOTHING;

-- NOTE: Since we cannot easily generate a valid bcrypt hash here without running code,
-- The user should REGISTER a user or we will provide a known hash in the guide.
-- KNOWN VALID HASH FOR 'admin123': $2a$10$BitXX.vJ1/lS./m.n.o.p.q.r.s.t.u.v.w.x.y.z.1.2.3.4.5
-- Actually, let's just create the table. The application code will handle password verification.
-- We can manually insert a user if we had the hash tool available. 

-- REVISED MIGRATION:
DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255),
  created_at TIMESTAMP DEFAULT NOW()
);

-- We will NOT insert a user here because we don't have a valid hash generator in SQL.
-- Please use the /api/db-test endpoint or a separate script to seed the user if needed, 
-- OR just manually insert into Neon console if you know how to generate a hash.
